api_game_developer_index:
    path: /game_developers
    controller: App\Controller\Api\GameDeveloperController::index
    methods: [GET]

api_game_developer_create:
    path: /game_developers
    controller: App\Controller\Api\GameDeveloperController::create
    methods: [POST]

api_game_developer_update:
    path: /game_developers/{id}
    controller: App\Controller\Api\GameDeveloperController::update
    methods: [PUT]

api_game_developer_delete:
    path: /game_developers/{id}
    controller: App\Controller\Api\GameDeveloperController::delete
    methods: [DELETE]
