api_video_game_index:
    path: /video_games
    controller: App\Controller\Api\VideoGameController::index
    methods: [GET]

api_video_game_create:
    path: /video_games
    controller: App\Controller\Api\VideoGameController::create
    methods: [POST]

api_video_game_igdb_search:
    path: /video_games/igdb/search
    controller: App\Controller\Api\VideoGameController::searchIgdb
    methods: [GET]

api_video_game_igdb_import:
    path: /video_games/igdb/import
    controller: App\Controller\Api\VideoGameController::createByIgdb
    methods: [POST]

api_video_game_igdb_show:
    path: /video_games/show/{id}
    controller: App\Controller\Api\VideoGameController::show
    methods: [GET]

api_video_game_rating:
    path: /video_games/rating/{id}
    controller: App\Controller\Api\VideoGameController::rating
    methods: [PATCH]

api_video_game_delete:
    path: /video_games/delete/{id}
    controller: App\Controller\Api\VideoGameController::delete
    methods: [DELETE]
