# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers
    
languages:
    prefix: /api
    resource: 'routes/languages.yaml'

category:
    prefix: /api
    resource: 'routes/category.yaml'

dictionnary:
    prefix: /api
    resource: 'routes/dictionnary.yaml'

editor:
    prefix: /api
    resource: 'routes/api/editor.yaml'

developer:
    prefix: /api
    resource: 'routes/api/developer.yaml'

game-console:
    prefix: /api
    resource: 'routes/api/game_console.yaml'

game:
    prefix: /api
    resource: 'routes/api/video_game.yaml'

game-price-history:
    prefix: /api
    resource: 'routes/api/game_price_history.yaml'