name: Symfony CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: pdo_sqlite, sqlite3

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: |
            vendor
            ~/.composer/cache
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Create baseline .env
        run: |
          echo "APP_ENV=test" > .env
          echo "APP_SECRET=67d3a393e185088c4b6c31f6df2b8fbc" >> .env
          echo "DEFAULT_URI=http://localhost" >> .env

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress --no-scripts

      - name: Run Pint
        run: ./vendor/bin/pint --test -v

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: pdo_sqlite, sqlite3

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: |
            vendor
            ~/.composer/cache
          key: composer-${{ hashFiles('composer.lock') }}

      # REAJOUT : Nécessaire pour le dump-env juste après
      - name: Create baseline .env
        run: |
          echo "APP_ENV=test" > .env
          echo "APP_SECRET=67d3a393e185088c4b6c31f6df2b8fbc" >> .env
          echo "DEFAULT_URI=http://localhost" >> .env

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress --no-scripts

      - name: Dump Env
        run: composer dump-env test

      - name: Install PHPUnit Bridge
        run: php vendor/symfony/phpunit-bridge/bin/simple-phpunit --version

      - name: Prepare test database
        run: |
          php bin/console doctrine:schema:drop --env=test --force --full-database
          php bin/console doctrine:schema:create --env=test

      # CORRECTION : Chemin nettoyé ici
      - name: Run tests
        env:
          SYMFONY_DEPRECATIONS_HELPER: disabled
        run: php vendor/symfony/phpunit-bridge/bin/simple-phpunit tests/Functional
